# quiz_data.py

quiz_data = [
    {"question": "What is the unit of electrical resistance?", "options": ["Ohm", "Volt", "Ampere", "Watt"], "answer": "Ohm"},
    {"question": "Which component stores electrical energy?", "options": ["Resistor", "Capacitor", "Diode", "Transistor"], "answer": "Capacitor"},
    {"question": "What does LED stand for?", "options": ["Light Emitting Diode", "Light Energy Device", "Low Emission Diode", "Light Electron Device"], "answer": "Light Emitting Diode"},
    {"question": "Which device converts AC to DC?", "options": ["Transformer", "Rectifier", "Inductor", "Capacitor"], "answer": "Rectifier"},
    {"question": "What is the function of a resistor?", "options": ["Store charge", "Resist current flow", "Amplify signal", "Convert AC to DC"], "answer": "Resist current flow"},
    {"question": "Which component is used to amplify signals?", "options": ["Diode", "Transistor", "Capacitor", "LED"], "answer": "Transistor"},
    {"question": "Which material is commonly used as a conductor?", "options": ["Copper", "Rubber", "Glass", "Plastic"], "answer": "Copper"},
    {"question": "What does a capacitor block?", "options": ["AC", "DC", "Current", "Voltage"], "answer": "DC"},
    {"question": "Which component allows current to flow in one direction?", "options": ["Resistor", "Inductor", "Diode", "Transistor"], "answer": "Diode"},
    {"question": "What is the unit of electric current?", "options": ["Ampere", "Volt", "Ohm", "Watt"], "answer": "Ampere"},
    {"question": "Which law relates voltage, current, and resistance?", "options": ["Ohm's Law", "Kirchhoff's Law", "Faraday's Law", "Coulomb's Law"], "answer": "Ohm's Law"},
    {"question": "What is the main function of a transformer?", "options": ["Convert AC to DC", "Change voltage level", "Amplify signals", "Store energy"], "answer": "Change voltage level"},
    {"question": "Which type of transistor has three terminals?", "options": ["BJT", "Diode", "LED", "Resistor"], "answer": "BJT"},
    {"question": "Which device is used to measure voltage?", "options": ["Ammeter", "Voltmeter", "Ohmmeter", "Multimeter"], "answer": "Voltmeter"},
    {"question": "Which device is used to measure current?", "options": ["Voltmeter", "Ammeter", "Wattmeter", "Oscilloscope"], "answer": "Ammeter"},
    {"question": "What is the color code for a 1kΩ resistor?", "options": ["Brown, Black, Red", "Red, Red, Brown", "Orange, Orange, Black", "Green, Blue, Brown"], "answer": "Brown, Black, Red"},
    {"question": "Which component opposes changes in current?", "options": ["Resistor", "Capacitor", "Inductor", "Diode"], "answer": "Inductor"},
    {"question": "What is the function of a fuse?", "options": ["Amplify signal", "Protect circuits from overcurrent", "Store energy", "Convert AC to DC"], "answer": "Protect circuits from overcurrent"},
    {"question": "Which device can be used to display waveforms?", "options": ["Multimeter", "Oscilloscope", "Voltmeter", "Ammeter"], "answer": "Oscilloscope"},
    {"question": "Which type of diode emits light when current passes through?", "options": ["Zener Diode", "LED", "Photodiode", "Tunnel Diode"], "answer": "LED"},
    {"question": "Which type of diode allows current to flow in reverse at a certain voltage?", "options": ["LED", "Zener Diode", "Schottky Diode", "Tunnel Diode"], "answer": "Zener Diode"},
    {"question": "What is the main function of a rectifier?", "options": ["Store energy", "Convert AC to DC", "Amplify signals", "Reduce resistance"], "answer": "Convert AC to DC"},
    {"question": "Which type of capacitor is polarized?", "options": ["Ceramic", "Electrolytic", "Film", "Paper"], "answer": "Electrolytic"},
    {"question": "What is the function of a variable resistor?", "options": ["Store charge", "Adjust current", "Amplify voltage", "Convert AC to DC"], "answer": "Adjust current"},
    {"question": "Which component converts electrical energy into mechanical energy?", "options": ["Motor", "Generator", "Transistor", "Diode"], "answer": "Motor"},
    {"question": "Which device converts mechanical energy into electrical energy?", "options": ["Motor", "Generator", "Capacitor", "Resistor"], "answer": "Generator"},
    {"question": "What is the function of a relay?", "options": ["Switch using an electromagnetic coil", "Store charge", "Measure voltage", "Reduce current"], "answer": "Switch using an electromagnetic coil"},
    {"question": "Which component can store energy in an electric field?", "options": ["Inductor", "Capacitor", "Resistor", "Diode"], "answer": "Capacitor"},
    {"question": "Which component can store energy in a magnetic field?", "options": ["Resistor", "Inductor", "Capacitor", "Diode"], "answer": "Inductor"},
    {"question": "What is the main function of a microcontroller?", "options": ["Amplify signals", "Process data and control devices", "Store energy", "Measure voltage"], "answer": "Process data and control devices"},
    {"question": "Which IC is used for logic operations?", "options": ["Op-amp", "Logic gate IC", "Timer IC", "Voltage regulator IC"], "answer": "Logic gate IC"},
    {"question": "What is the function of a voltage regulator?", "options": ["Convert AC to DC", "Maintain constant voltage", "Amplify signal", "Switch current"], "answer": "Maintain constant voltage"},
    {"question": "Which device is used to protect circuits from high voltage spikes?", "options": ["Fuse", "MOV (Metal Oxide Varistor)", "Resistor", "LED"], "answer": "MOV (Metal Oxide Varistor)"},
    {"question": "Which component allows alternating current to pass but blocks direct current?", "options": ["Resistor", "Capacitor", "Inductor", "Diode"], "answer": "Capacitor"},
    {"question": "What is the main function of a Schmitt Trigger?", "options": ["Convert AC to DC", "Provide hysteresis for a digital signal", "Amplify signal", "Reduce voltage"], "answer": "Provide hysteresis for a digital signal"},
    {"question": "Which type of memory is volatile?", "options": ["RAM", "ROM", "EEPROM", "Flash"], "answer": "RAM"},
    {"question": "Which type of memory retains data without power?", "options": ["RAM", "ROM", "Cache", "Register"], "answer": "ROM"},
    {"question": "Which logic gate outputs HIGH only when all inputs are HIGH?", "options": ["OR", "AND", "NAND", "NOR"], "answer": "AND"},
    {"question": "Which logic gate outputs LOW only when all inputs are HIGH?", "options": ["NAND", "AND", "OR", "NOR"], "answer": "NAND"},
    {"question": "Which logic gate outputs HIGH when at least one input is HIGH?", "options": ["AND", "OR", "NOR", "XOR"], "answer": "OR"},
    {"question": "Which logic gate outputs HIGH when inputs are different?", "options": ["XOR", "OR", "AND", "NOR"], "answer": "XOR"},
    {"question": "Which component is used for timing applications?", "options": ["Transistor", "555 Timer IC", "LED", "Resistor"], "answer": "555 Timer IC"},
    {"question": "Which type of motor requires DC supply?", "options": ["AC Induction Motor", "DC Motor", "Synchronous Motor", "Stepper Motor"], "answer": "DC Motor"},
    {"question": "Which type of motor is controlled by pulses?", "options": ["Stepper Motor", "DC Motor", "AC Motor", "Synchronous Motor"], "answer": "Stepper Motor"},
    {"question": "What is the main use of a transistor in electronics?", "options": ["Amplifier and switch", "Voltage storage", "Current measurement", "Light emission"], "answer": "Amplifier and switch"},
    {"question": "Which device converts sound energy to electrical signals?", "options": ["Microphone", "Speaker", "LED", "Transistor"], "answer": "Microphone"},
    {"question": "Which device converts electrical signals to sound?", "options": ["Speaker", "Microphone", "Capacitor", "Diode"], "answer": "Speaker"},
    {"question": "Which IC is commonly used for operational amplification?", "options": ["Op-amp IC", "Logic IC", "Timer IC", "Voltage regulator IC"], "answer": "Op-amp IC"},
    {"question": "Which type of diode is used in high-frequency applications?", "options": ["Schottky Diode", "Zener Diode", "LED", "Tunnel Diode"], "answer": "Schottky Diode"},
    {"question": "Which component is used to filter ripples in a power supply?", "options": ["Resistor", "Capacitor", "Diode", "Transistor"], "answer": "Capacitor"},
    {"question": "Which type of transformer is used in power supplies?", "options": ["Step-up Transformer", "Step-down Transformer", "Isolation Transformer", "All of these"], "answer": "All of these"},
    {"question": "Which device protects a circuit against reverse polarity?", "options": ["Fuse", "Diode", "Resistor", "Capacitor"], "answer": "Diode"},
    {"question": "Which device senses light and converts it into current?", "options": ["Photodiode", "LED", "Phototransistor", "LDR"], "answer": "Photodiode"},
    {"question": "Which device changes resistance with light intensity?", "options": ["Photodiode", "LDR", "LED", "Phototransistor"], "answer": "LDR"},
    {"question": "Which IC is used for analog-to-digital conversion?", "options": ["ADC IC", "DAC IC", "Op-amp IC", "Timer IC"], "answer": "ADC IC"},
    {"question": "Which IC is used for digital-to-analog conversion?", "options": ["DAC IC", "ADC IC", "Op-amp IC", "Timer IC"], "answer": "DAC IC"},
    {"question": "Which type of diode is used for voltage regulation?", "options": ["Zener Diode", "LED", "Schottky Diode", "Tunnel Diode"], "answer": "Zener Diode"},
    {"question": "Which component reduces current flow in a circuit?", "options": ["Resistor", "Capacitor", "Inductor", "Diode"], "answer": "Resistor"},
    {"question": "Which IC is used in 7-segment displays?", "options": ["Decoder IC", "Op-amp IC", "Timer IC", "Logic IC"], "answer": "Decoder IC"},
    {"question": "Which type of IC contains analog and digital circuits?", "options": ["Mixed-signal IC", "Digital IC", "Analog IC", "Power IC"], "answer": "Mixed-signal IC"},
    {"question": "Which component is used to store charge temporarily?", "options": ["Resistor", "Capacitor", "Inductor", "Diode"], "answer": "Capacitor"},
    {"question": "Which device is used to control high voltage using low voltage?", "options": ["Relay", "Diode", "Resistor", "Capacitor"], "answer": "Relay"},
    {"question": "Which type of diode is used in RF applications?", "options": ["Varactor Diode", "Zener Diode", "LED", "Schottky Diode"], "answer": "Varactor Diode"},
    {"question": "Which component converts chemical energy to electrical energy?", "options": ["Battery", "Capacitor", "Diode", "Resistor"], "answer": "Battery"},
    {"question": "Which type of battery is rechargeable?", "options": ["Li-ion", "Alkaline", "Zinc-carbon", "Dry Cell"], "answer": "Li-ion"},
    {"question": "Which type of battery is non-rechargeable?", "options": ["Li-ion", "Alkaline", "Lead-acid", "NiMH"], "answer": "Alkaline"},
    {"question": "Which component protects circuits from excessive current?", "options": ["Fuse", "Diode", "Resistor", "Capacitor"], "answer": "Fuse"},
    {"question": "Which device can sense temperature changes?", "options": ["Thermistor", "LDR", "Photodiode", "LED"], "answer": "Thermistor"},
    {"question": "Which device changes resistance with temperature?", "options": ["Thermistor", "LDR", "LED", "Diode"], "answer": "Thermistor"},
    {"question": "Which IC is used in timers and oscillators?", "options": ["555 Timer IC", "Op-amp IC", "Logic IC", "Voltage regulator IC"], "answer": "555 Timer IC"},
    {"question": "Which component is used to amplify weak signals?", "options": ["Transistor", "Diode", "Resistor", "Capacitor"], "answer": "Transistor"},
    {"question": "Which device converts sunlight into electricity?", "options": ["Solar Cell", "LED", "Photodiode", "Battery"], "answer": "Solar Cell"},
    {"question": "Which device is used to invert logic levels?", "options": ["NOT Gate", "AND Gate", "OR Gate", "XOR Gate"], "answer": "NOT Gate"},
    {"question": "Which gate outputs HIGH only when both inputs are LOW?", "options": ["NOR Gate", "AND Gate", "OR Gate", "XOR Gate"], "answer": "NOR Gate"},
    {"question": "Which IC is commonly used for operational integration and differentiation?", "options": ["Op-amp IC", "Logic IC", "Timer IC", "Voltage regulator IC"], "answer": "Op-amp IC"},
    {"question": "Which device is used for short-circuit protection?", "options": ["Fuse", "Relay", "Diode", "Transistor"], "answer": "Fuse"},
    {"question": "Which component is used to filter high-frequency noise?", "options": ["Capacitor", "Inductor", "Resistor", "Diode"], "answer": "Capacitor"},
    {"question": "Which type of diode has very fast switching speed?", "options": ["Schottky Diode", "Zener Diode", "LED", "Tunnel Diode"], "answer": "Schottky Diode"},
    {"question": "Which IC is used in digital counters?", "options": ["Counter IC", "Op-amp IC", "Timer IC", "Voltage regulator IC"], "answer": "Counter IC"},
    {"question": "Which device is used to sense light intensity?", "options": ["LDR", "Photodiode", "LED", "Thermistor"], "answer": "LDR"},
    {"question": "Which component allows bidirectional current flow?", "options": ["Resistor", "Diode", "Triac", "Capacitor"], "answer": "Triac"},
    {"question": "Which type of diode is used in microwave circuits?", "options": ["Tunnel Diode", "Zener Diode", "LED", "Schottky Diode"], "answer": "Tunnel Diode"},
    {"question": "Which IC is used to generate clock pulses?", "options": ["555 Timer IC", "Op-amp IC", "Logic IC", "Voltage regulator IC"], "answer": "555 Timer IC"},
    {"question": "Which device converts AC to DC in power supplies?", "options": ["Rectifier", "Transformer", "Capacitor", "Transistor"], "answer": "Rectifier"},
    {"question": "Which component stores energy in a magnetic field?", "options": ["Inductor", "Capacitor", "Resistor", "Diode"], "answer": "Inductor"},
    {"question": "Which device is used to amplify audio signals?", "options": ["Transistor Amplifier", "Diode", "Capacitor", "Resistor"], "answer": "Transistor Amplifier"},
    {"question": "Which component is used for voltage step-up or step-down?", "options": ["Transformer", "Diode", "Capacitor", "Resistor"], "answer": "Transformer"},
    {"question": "Which IC is used for analog signal comparison?", "options": ["Op-amp as Comparator", "Logic IC", "Timer IC", "Voltage regulator IC"], "answer": "Op-amp as Comparator"},
]
